defaults: &defaults
  adapter: mysql2
  encoding: utf8
  port: 3306
  # Pool size is matched to number of worker threads
  pool: 16
  # Don't use prepared statements with pgBouncer transaction pooling
  prepared_statements: false
  properties:
    prepareThreshold: 0

development:
  <<: *defaults
  host: localhost
  database: standards

# test:
#   <<: *defaults
#   host: localhost
#   database: backpack_test

# production:
#   <<: *defaults
#   host:
#   port:
#   database:
#   username:
#   password:
